### ISSUE TITLE
Tabs.add(String) exists, but using it causes an exception

### ISSUE THREAD

**Issue by johannesh2** [vaadin/vaadin-tabs-flow#116]
`IllegalStateException` is thrown at some point when using Tabs.add(String).

**Comment by rolandoisidoro** [comment]
I stumbled upon this issue while adding a string before any Tab to a Tabs component. The following example:

```
Tabs tabs = new Tabs();
tabs.add("Some string");
tabs.add(new Tab("Tab 1"));
tabs.add(new Tab("Tab 1"));
```

throws a `IllegalStateException`:
```
java.lang.IllegalStateException: Illegal component inside Tabs: com.vaadin.flow.component.Text@4e10fa58
	at com.vaadin.flow.component.tabs.Tabs.getSelectedTab(Tabs.java:359)
	at com.vaadin.flow.component.tabs.Tabs.updateSelectedTab(Tabs.java:471)
```

Looking into the [source code](https://github.com/vaadin/vaadin-tabs-flow/blob/master/vaadin-tabs-flow/src/main/java/com/vaadin/flow/component/tabs/Tabs.java#L358), this occurs when the selected component is not an instance of the `Tab` component.

**Comment by rolandoisidoro** [comment]
Since `Tabs` implements the `HasOrderedComponents` interface, that extends the `HasComponents` interface, which provides [`add(Component... components)`](https://github.com/vaadin/flow/blob/master/flow-server/src/main/java/com/vaadin/flow/component/HasComponents.java#L48) for generic components and [`void add(String text)`](https://github.com/vaadin/flow/blob/master/flow-server/src/main/java/com/vaadin/flow/component/HasComponents.java#L63) for strings.

I consider this to be a major issue, since the `IllegalStateException` occurs when using common Vaadin component functions. As is, we're limited to simply add `Tab` components to `Tabs`. Any chance this gets reviewed?
