### ISSUE TITLE
Support for all tabs unselected

### ISSUE THREAD

**Issue by heruan** [vaadin/vaadin-tabs-flow#72]
Using `Tabs` for navigation purposes, sometimes users may be in a location where none of the tabs represent where they are. In that cases, it would be useful to unselect all tabs. This is possibile in the Web Component setting the selected index to `-1`, but in Flow you get an `IllegalArgumenException`:

```
java.lang.IllegalArgumentException: The 'index' argument should be greater than 0. It was: -1
	at com.vaadin.flow.component.HasOrderedComponents.getComponentAt(HasOrderedComponents.java:123)
	at com.vaadin.flow.component.tabs.Tabs.getSelectedTab(Tabs.java:151)
	at com.vaadin.flow.component.tabs.Tabs.updateSelectedTab(Tabs.java:237)
	at com.vaadin.flow.component.tabs.Tabs.lambda$new$c53a20e4$1(Tabs.java:58)
	at com.vaadin.flow.internal.nodefeature.ElementPropertyMap.lambda$fireEvent$5(ElementPropertyMap.java:402)
	at java.util.ArrayList.forEach(ArrayList.java:1378)
	at com.vaadin.flow.internal.nodefeature.ElementPropertyMap.fireEvent(ElementPropertyMap.java:402)
	at com.vaadin.flow.internal.nodefeature.ElementPropertyMap.access$100(ElementPropertyMap.java:48)
	at com.vaadin.flow.internal.nodefeature.ElementPropertyMap$PutResult.run(ElementPropertyMap.java:170)
	at com.vaadin.flow.internal.nodefeature.ElementPropertyMap.put(ElementPropertyMap.java:152)
	at com.vaadin.flow.internal.nodefeature.AbstractPropertyMap.setProperty(AbstractPropertyMap.java:60)
	at com.vaadin.flow.internal.nodefeature.ElementPropertyMap.setProperty(ElementPropertyMap.java:107)
	at com.vaadin.flow.dom.impl.BasicElementStateProvider.setProperty(BasicElementStateProvider.java:248)
	at com.vaadin.flow.dom.Element.setRawProperty(Element.java:724)
	at com.vaadin.flow.dom.Element.setProperty(Element.java:667)
	at com.vaadin.flow.component.tabs.Tabs.setSelectedIndex(Tabs.java:141)
```

Possibly related to https://github.com/vaadin/vaadin-tabs-flow/issues/70

**Comment by pekam** [comment]
Thanks for reporting the issue @heruan!

We just released `vaadin-tabs-flow` version `1.0.5`, which includes the fix for this. So you can already take it into use if you need this functionality before the next platform release.
